### ISSUE TITLE
Sigh

### ISSUE THREAD

**Issue by PowerPress** [r3dsh1ft/RedzSIGINT#3]
Been another 8 months and still no updates. Looked like a great project and I'm sure the exposure was great. Please upload the files so this can used or just take down the site and remove the GitHub. Might as well just make your site redirect to the LinkedIn page. Sorry if that sounds like being a dick but its become the norm for people to promise the world and get lots of media exposure and then never follow through. Leaving the page up just gives people false hope of a promise that has no intention of being fulfilled.

**Comment by iamredshift** [comment]
I have been super busy that is for sure. 
I will be updating some items on the GIT including the build list later this week.
I had ever intention to fulfill this project, just building an open source SIGINT platform has not what pays the bills, so I have to prioritize other items over this.
